version: "3.9"

services:
  nezhaguard:
    build: .
    image: nezhaguard:latest
    container_name: nezhaguard
    hostname: nezhaguard-siem
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      - NEZHA_SHOW_GUI=0
      - NEZHA_INTERFACE=eth0
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config:/etc/nezhaguard/config:ro
      - ./rules:/etc/nezhaguard/rules:ro
      - /var/log:/var/log:ro
    command: ["-v"]
