# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/johnmelodyme/Documents/ctkqiang/NezhaGuard/test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/johnmelodyme/Documents/ctkqiang/NezhaGuard

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/johnmelodyme/Documents/ctkqiang/NezhaGuard/CMakeFiles /Users/johnmelodyme/Documents/ctkqiang/NezhaGuard//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/johnmelodyme/Documents/ctkqiang/NezhaGuard/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NezhaGuardTests

# Build rule for target.
NezhaGuardTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NezhaGuardTests
.PHONY : NezhaGuardTests

# fast build rule for target.
NezhaGuardTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/build
.PHONY : NezhaGuardTests/fast

#=============================================================================
# Target rules for targets named NezhaGuardTests_autogen_timestamp_deps

# Build rule for target.
NezhaGuardTests_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NezhaGuardTests_autogen_timestamp_deps
.PHONY : NezhaGuardTests_autogen_timestamp_deps

# fast build rule for target.
NezhaGuardTests_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests_autogen_timestamp_deps.dir/build.make CMakeFiles/NezhaGuardTests_autogen_timestamp_deps.dir/build
.PHONY : NezhaGuardTests_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named NezhaGuardTests_autogen

# Build rule for target.
NezhaGuardTests_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NezhaGuardTests_autogen
.PHONY : NezhaGuardTests_autogen

# fast build rule for target.
NezhaGuardTests_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests_autogen.dir/build.make CMakeFiles/NezhaGuardTests_autogen.dir/build
.PHONY : NezhaGuardTests_autogen/fast

NezhaGuardTests_autogen/mocs_compilation.o: NezhaGuardTests_autogen/mocs_compilation.cpp.o
.PHONY : NezhaGuardTests_autogen/mocs_compilation.o

# target to build an object file
NezhaGuardTests_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/NezhaGuardTests_autogen/mocs_compilation.cpp.o
.PHONY : NezhaGuardTests_autogen/mocs_compilation.cpp.o

NezhaGuardTests_autogen/mocs_compilation.i: NezhaGuardTests_autogen/mocs_compilation.cpp.i
.PHONY : NezhaGuardTests_autogen/mocs_compilation.i

# target to preprocess a source file
NezhaGuardTests_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/NezhaGuardTests_autogen/mocs_compilation.cpp.i
.PHONY : NezhaGuardTests_autogen/mocs_compilation.cpp.i

NezhaGuardTests_autogen/mocs_compilation.s: NezhaGuardTests_autogen/mocs_compilation.cpp.s
.PHONY : NezhaGuardTests_autogen/mocs_compilation.s

# target to generate assembly for a file
NezhaGuardTests_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/NezhaGuardTests_autogen/mocs_compilation.cpp.s
.PHONY : NezhaGuardTests_autogen/mocs_compilation.cpp.s

src/core/active_response.o: src/core/active_response.cc.o
.PHONY : src/core/active_response.o

# target to build an object file
src/core/active_response.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/active_response.cc.o
.PHONY : src/core/active_response.cc.o

src/core/active_response.i: src/core/active_response.cc.i
.PHONY : src/core/active_response.i

# target to preprocess a source file
src/core/active_response.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/active_response.cc.i
.PHONY : src/core/active_response.cc.i

src/core/active_response.s: src/core/active_response.cc.s
.PHONY : src/core/active_response.s

# target to generate assembly for a file
src/core/active_response.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/active_response.cc.s
.PHONY : src/core/active_response.cc.s

src/core/alert.o: src/core/alert.cc.o
.PHONY : src/core/alert.o

# target to build an object file
src/core/alert.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/alert.cc.o
.PHONY : src/core/alert.cc.o

src/core/alert.i: src/core/alert.cc.i
.PHONY : src/core/alert.i

# target to preprocess a source file
src/core/alert.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/alert.cc.i
.PHONY : src/core/alert.cc.i

src/core/alert.s: src/core/alert.cc.s
.PHONY : src/core/alert.s

# target to generate assembly for a file
src/core/alert.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/alert.cc.s
.PHONY : src/core/alert.cc.s

src/core/arena.o: src/core/arena.cc.o
.PHONY : src/core/arena.o

# target to build an object file
src/core/arena.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/arena.cc.o
.PHONY : src/core/arena.cc.o

src/core/arena.i: src/core/arena.cc.i
.PHONY : src/core/arena.i

# target to preprocess a source file
src/core/arena.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/arena.cc.i
.PHONY : src/core/arena.cc.i

src/core/arena.s: src/core/arena.cc.s
.PHONY : src/core/arena.s

# target to generate assembly for a file
src/core/arena.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/arena.cc.s
.PHONY : src/core/arena.cc.s

src/core/capture.o: src/core/capture.cc.o
.PHONY : src/core/capture.o

# target to build an object file
src/core/capture.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/capture.cc.o
.PHONY : src/core/capture.cc.o

src/core/capture.i: src/core/capture.cc.i
.PHONY : src/core/capture.i

# target to preprocess a source file
src/core/capture.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/capture.cc.i
.PHONY : src/core/capture.cc.i

src/core/capture.s: src/core/capture.cc.s
.PHONY : src/core/capture.s

# target to generate assembly for a file
src/core/capture.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/capture.cc.s
.PHONY : src/core/capture.cc.s

src/core/decoder.o: src/core/decoder.cc.o
.PHONY : src/core/decoder.o

# target to build an object file
src/core/decoder.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/decoder.cc.o
.PHONY : src/core/decoder.cc.o

src/core/decoder.i: src/core/decoder.cc.i
.PHONY : src/core/decoder.i

# target to preprocess a source file
src/core/decoder.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/decoder.cc.i
.PHONY : src/core/decoder.cc.i

src/core/decoder.s: src/core/decoder.cc.s
.PHONY : src/core/decoder.s

# target to generate assembly for a file
src/core/decoder.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/decoder.cc.s
.PHONY : src/core/decoder.cc.s

src/core/detector.o: src/core/detector.cc.o
.PHONY : src/core/detector.o

# target to build an object file
src/core/detector.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/detector.cc.o
.PHONY : src/core/detector.cc.o

src/core/detector.i: src/core/detector.cc.i
.PHONY : src/core/detector.i

# target to preprocess a source file
src/core/detector.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/detector.cc.i
.PHONY : src/core/detector.cc.i

src/core/detector.s: src/core/detector.cc.s
.PHONY : src/core/detector.s

# target to generate assembly for a file
src/core/detector.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/detector.cc.s
.PHONY : src/core/detector.cc.s

src/core/event.o: src/core/event.cc.o
.PHONY : src/core/event.o

# target to build an object file
src/core/event.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/event.cc.o
.PHONY : src/core/event.cc.o

src/core/event.i: src/core/event.cc.i
.PHONY : src/core/event.i

# target to preprocess a source file
src/core/event.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/event.cc.i
.PHONY : src/core/event.cc.i

src/core/event.s: src/core/event.cc.s
.PHONY : src/core/event.s

# target to generate assembly for a file
src/core/event.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/event.cc.s
.PHONY : src/core/event.cc.s

src/core/geo_ip.o: src/core/geo_ip.cc.o
.PHONY : src/core/geo_ip.o

# target to build an object file
src/core/geo_ip.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/geo_ip.cc.o
.PHONY : src/core/geo_ip.cc.o

src/core/geo_ip.i: src/core/geo_ip.cc.i
.PHONY : src/core/geo_ip.i

# target to preprocess a source file
src/core/geo_ip.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/geo_ip.cc.i
.PHONY : src/core/geo_ip.cc.i

src/core/geo_ip.s: src/core/geo_ip.cc.s
.PHONY : src/core/geo_ip.s

# target to generate assembly for a file
src/core/geo_ip.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/geo_ip.cc.s
.PHONY : src/core/geo_ip.cc.s

src/core/honeypot.o: src/core/honeypot.cc.o
.PHONY : src/core/honeypot.o

# target to build an object file
src/core/honeypot.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/honeypot.cc.o
.PHONY : src/core/honeypot.cc.o

src/core/honeypot.i: src/core/honeypot.cc.i
.PHONY : src/core/honeypot.i

# target to preprocess a source file
src/core/honeypot.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/honeypot.cc.i
.PHONY : src/core/honeypot.cc.i

src/core/honeypot.s: src/core/honeypot.cc.s
.PHONY : src/core/honeypot.s

# target to generate assembly for a file
src/core/honeypot.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/honeypot.cc.s
.PHONY : src/core/honeypot.cc.s

src/core/ipaddr.o: src/core/ipaddr.cc.o
.PHONY : src/core/ipaddr.o

# target to build an object file
src/core/ipaddr.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/ipaddr.cc.o
.PHONY : src/core/ipaddr.cc.o

src/core/ipaddr.i: src/core/ipaddr.cc.i
.PHONY : src/core/ipaddr.i

# target to preprocess a source file
src/core/ipaddr.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/ipaddr.cc.i
.PHONY : src/core/ipaddr.cc.i

src/core/ipaddr.s: src/core/ipaddr.cc.s
.PHONY : src/core/ipaddr.s

# target to generate assembly for a file
src/core/ipaddr.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/ipaddr.cc.s
.PHONY : src/core/ipaddr.cc.s

src/core/log_watcher.o: src/core/log_watcher.cc.o
.PHONY : src/core/log_watcher.o

# target to build an object file
src/core/log_watcher.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/log_watcher.cc.o
.PHONY : src/core/log_watcher.cc.o

src/core/log_watcher.i: src/core/log_watcher.cc.i
.PHONY : src/core/log_watcher.i

# target to preprocess a source file
src/core/log_watcher.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/log_watcher.cc.i
.PHONY : src/core/log_watcher.cc.i

src/core/log_watcher.s: src/core/log_watcher.cc.s
.PHONY : src/core/log_watcher.s

# target to generate assembly for a file
src/core/log_watcher.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/log_watcher.cc.s
.PHONY : src/core/log_watcher.cc.s

src/core/net_util.o: src/core/net_util.cc.o
.PHONY : src/core/net_util.o

# target to build an object file
src/core/net_util.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/net_util.cc.o
.PHONY : src/core/net_util.cc.o

src/core/net_util.i: src/core/net_util.cc.i
.PHONY : src/core/net_util.i

# target to preprocess a source file
src/core/net_util.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/net_util.cc.i
.PHONY : src/core/net_util.cc.i

src/core/net_util.s: src/core/net_util.cc.s
.PHONY : src/core/net_util.s

# target to generate assembly for a file
src/core/net_util.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/net_util.cc.s
.PHONY : src/core/net_util.cc.s

src/core/rule_loader.o: src/core/rule_loader.cc.o
.PHONY : src/core/rule_loader.o

# target to build an object file
src/core/rule_loader.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/rule_loader.cc.o
.PHONY : src/core/rule_loader.cc.o

src/core/rule_loader.i: src/core/rule_loader.cc.i
.PHONY : src/core/rule_loader.i

# target to preprocess a source file
src/core/rule_loader.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/rule_loader.cc.i
.PHONY : src/core/rule_loader.cc.i

src/core/rule_loader.s: src/core/rule_loader.cc.s
.PHONY : src/core/rule_loader.s

# target to generate assembly for a file
src/core/rule_loader.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/rule_loader.cc.s
.PHONY : src/core/rule_loader.cc.s

src/core/tor_checker.o: src/core/tor_checker.cc.o
.PHONY : src/core/tor_checker.o

# target to build an object file
src/core/tor_checker.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/tor_checker.cc.o
.PHONY : src/core/tor_checker.cc.o

src/core/tor_checker.i: src/core/tor_checker.cc.i
.PHONY : src/core/tor_checker.i

# target to preprocess a source file
src/core/tor_checker.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/tor_checker.cc.i
.PHONY : src/core/tor_checker.cc.i

src/core/tor_checker.s: src/core/tor_checker.cc.s
.PHONY : src/core/tor_checker.s

# target to generate assembly for a file
src/core/tor_checker.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/tor_checker.cc.s
.PHONY : src/core/tor_checker.cc.s

src/core/webshell_scanner.o: src/core/webshell_scanner.cc.o
.PHONY : src/core/webshell_scanner.o

# target to build an object file
src/core/webshell_scanner.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/webshell_scanner.cc.o
.PHONY : src/core/webshell_scanner.cc.o

src/core/webshell_scanner.i: src/core/webshell_scanner.cc.i
.PHONY : src/core/webshell_scanner.i

# target to preprocess a source file
src/core/webshell_scanner.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/webshell_scanner.cc.i
.PHONY : src/core/webshell_scanner.cc.i

src/core/webshell_scanner.s: src/core/webshell_scanner.cc.s
.PHONY : src/core/webshell_scanner.s

# target to generate assembly for a file
src/core/webshell_scanner.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/core/webshell_scanner.cc.s
.PHONY : src/core/webshell_scanner.cc.s

src/service/database_helper.o: src/service/database_helper.cc.o
.PHONY : src/service/database_helper.o

# target to build an object file
src/service/database_helper.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/service/database_helper.cc.o
.PHONY : src/service/database_helper.cc.o

src/service/database_helper.i: src/service/database_helper.cc.i
.PHONY : src/service/database_helper.i

# target to preprocess a source file
src/service/database_helper.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/service/database_helper.cc.i
.PHONY : src/service/database_helper.cc.i

src/service/database_helper.s: src/service/database_helper.cc.s
.PHONY : src/service/database_helper.s

# target to generate assembly for a file
src/service/database_helper.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/service/database_helper.cc.s
.PHONY : src/service/database_helper.cc.s

src/utilities/logger.o: src/utilities/logger.cc.o
.PHONY : src/utilities/logger.o

# target to build an object file
src/utilities/logger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/utilities/logger.cc.o
.PHONY : src/utilities/logger.cc.o

src/utilities/logger.i: src/utilities/logger.cc.i
.PHONY : src/utilities/logger.i

# target to preprocess a source file
src/utilities/logger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/utilities/logger.cc.i
.PHONY : src/utilities/logger.cc.i

src/utilities/logger.s: src/utilities/logger.cc.s
.PHONY : src/utilities/logger.s

# target to generate assembly for a file
src/utilities/logger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/utilities/logger.cc.s
.PHONY : src/utilities/logger.cc.s

src/views/detail_panel.o: src/views/detail_panel.cc.o
.PHONY : src/views/detail_panel.o

# target to build an object file
src/views/detail_panel.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/views/detail_panel.cc.o
.PHONY : src/views/detail_panel.cc.o

src/views/detail_panel.i: src/views/detail_panel.cc.i
.PHONY : src/views/detail_panel.i

# target to preprocess a source file
src/views/detail_panel.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/views/detail_panel.cc.i
.PHONY : src/views/detail_panel.cc.i

src/views/detail_panel.s: src/views/detail_panel.cc.s
.PHONY : src/views/detail_panel.s

# target to generate assembly for a file
src/views/detail_panel.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/views/detail_panel.cc.s
.PHONY : src/views/detail_panel.cc.s

src/views/gui_sink.o: src/views/gui_sink.cc.o
.PHONY : src/views/gui_sink.o

# target to build an object file
src/views/gui_sink.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/views/gui_sink.cc.o
.PHONY : src/views/gui_sink.cc.o

src/views/gui_sink.i: src/views/gui_sink.cc.i
.PHONY : src/views/gui_sink.i

# target to preprocess a source file
src/views/gui_sink.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/views/gui_sink.cc.i
.PHONY : src/views/gui_sink.cc.i

src/views/gui_sink.s: src/views/gui_sink.cc.s
.PHONY : src/views/gui_sink.s

# target to generate assembly for a file
src/views/gui_sink.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/views/gui_sink.cc.s
.PHONY : src/views/gui_sink.cc.s

src/views/log_model.o: src/views/log_model.cc.o
.PHONY : src/views/log_model.o

# target to build an object file
src/views/log_model.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/views/log_model.cc.o
.PHONY : src/views/log_model.cc.o

src/views/log_model.i: src/views/log_model.cc.i
.PHONY : src/views/log_model.i

# target to preprocess a source file
src/views/log_model.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/views/log_model.cc.i
.PHONY : src/views/log_model.cc.i

src/views/log_model.s: src/views/log_model.cc.s
.PHONY : src/views/log_model.s

# target to generate assembly for a file
src/views/log_model.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/src/views/log_model.cc.s
.PHONY : src/views/log_model.cc.s

test_arena.o: test_arena.cc.o
.PHONY : test_arena.o

# target to build an object file
test_arena.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_arena.cc.o
.PHONY : test_arena.cc.o

test_arena.i: test_arena.cc.i
.PHONY : test_arena.i

# target to preprocess a source file
test_arena.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_arena.cc.i
.PHONY : test_arena.cc.i

test_arena.s: test_arena.cc.s
.PHONY : test_arena.s

# target to generate assembly for a file
test_arena.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_arena.cc.s
.PHONY : test_arena.cc.s

test_ipaddr.o: test_ipaddr.cc.o
.PHONY : test_ipaddr.o

# target to build an object file
test_ipaddr.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_ipaddr.cc.o
.PHONY : test_ipaddr.cc.o

test_ipaddr.i: test_ipaddr.cc.i
.PHONY : test_ipaddr.i

# target to preprocess a source file
test_ipaddr.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_ipaddr.cc.i
.PHONY : test_ipaddr.cc.i

test_ipaddr.s: test_ipaddr.cc.s
.PHONY : test_ipaddr.s

# target to generate assembly for a file
test_ipaddr.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_ipaddr.cc.s
.PHONY : test_ipaddr.cc.s

test_log_model.o: test_log_model.cc.o
.PHONY : test_log_model.o

# target to build an object file
test_log_model.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_log_model.cc.o
.PHONY : test_log_model.cc.o

test_log_model.i: test_log_model.cc.i
.PHONY : test_log_model.i

# target to preprocess a source file
test_log_model.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_log_model.cc.i
.PHONY : test_log_model.cc.i

test_log_model.s: test_log_model.cc.s
.PHONY : test_log_model.s

# target to generate assembly for a file
test_log_model.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_log_model.cc.s
.PHONY : test_log_model.cc.s

test_main.o: test_main.cc.o
.PHONY : test_main.o

# target to build an object file
test_main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_main.cc.o
.PHONY : test_main.cc.o

test_main.i: test_main.cc.i
.PHONY : test_main.i

# target to preprocess a source file
test_main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_main.cc.i
.PHONY : test_main.cc.i

test_main.s: test_main.cc.s
.PHONY : test_main.s

# target to generate assembly for a file
test_main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_main.cc.s
.PHONY : test_main.cc.s

test_rule_loader.o: test_rule_loader.cc.o
.PHONY : test_rule_loader.o

# target to build an object file
test_rule_loader.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_rule_loader.cc.o
.PHONY : test_rule_loader.cc.o

test_rule_loader.i: test_rule_loader.cc.i
.PHONY : test_rule_loader.i

# target to preprocess a source file
test_rule_loader.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_rule_loader.cc.i
.PHONY : test_rule_loader.cc.i

test_rule_loader.s: test_rule_loader.cc.s
.PHONY : test_rule_loader.s

# target to generate assembly for a file
test_rule_loader.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_rule_loader.cc.s
.PHONY : test_rule_loader.cc.s

test_theme.o: test_theme.cc.o
.PHONY : test_theme.o

# target to build an object file
test_theme.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_theme.cc.o
.PHONY : test_theme.cc.o

test_theme.i: test_theme.cc.i
.PHONY : test_theme.i

# target to preprocess a source file
test_theme.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_theme.cc.i
.PHONY : test_theme.cc.i

test_theme.s: test_theme.cc.s
.PHONY : test_theme.s

# target to generate assembly for a file
test_theme.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_theme.cc.s
.PHONY : test_theme.cc.s

test_types.o: test_types.cc.o
.PHONY : test_types.o

# target to build an object file
test_types.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_types.cc.o
.PHONY : test_types.cc.o

test_types.i: test_types.cc.i
.PHONY : test_types.i

# target to preprocess a source file
test_types.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_types.cc.i
.PHONY : test_types.cc.i

test_types.s: test_types.cc.s
.PHONY : test_types.s

# target to generate assembly for a file
test_types.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_types.cc.s
.PHONY : test_types.cc.s

test_webshell_scanner.o: test_webshell_scanner.cc.o
.PHONY : test_webshell_scanner.o

# target to build an object file
test_webshell_scanner.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_webshell_scanner.cc.o
.PHONY : test_webshell_scanner.cc.o

test_webshell_scanner.i: test_webshell_scanner.cc.i
.PHONY : test_webshell_scanner.i

# target to preprocess a source file
test_webshell_scanner.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_webshell_scanner.cc.i
.PHONY : test_webshell_scanner.cc.i

test_webshell_scanner.s: test_webshell_scanner.cc.s
.PHONY : test_webshell_scanner.s

# target to generate assembly for a file
test_webshell_scanner.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NezhaGuardTests.dir/build.make CMakeFiles/NezhaGuardTests.dir/test_webshell_scanner.cc.s
.PHONY : test_webshell_scanner.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... NezhaGuardTests_autogen"
	@echo "... NezhaGuardTests_autogen_timestamp_deps"
	@echo "... NezhaGuardTests"
	@echo "... NezhaGuardTests_autogen/mocs_compilation.o"
	@echo "... NezhaGuardTests_autogen/mocs_compilation.i"
	@echo "... NezhaGuardTests_autogen/mocs_compilation.s"
	@echo "... src/core/active_response.o"
	@echo "... src/core/active_response.i"
	@echo "... src/core/active_response.s"
	@echo "... src/core/alert.o"
	@echo "... src/core/alert.i"
	@echo "... src/core/alert.s"
	@echo "... src/core/arena.o"
	@echo "... src/core/arena.i"
	@echo "... src/core/arena.s"
	@echo "... src/core/capture.o"
	@echo "... src/core/capture.i"
	@echo "... src/core/capture.s"
	@echo "... src/core/decoder.o"
	@echo "... src/core/decoder.i"
	@echo "... src/core/decoder.s"
	@echo "... src/core/detector.o"
	@echo "... src/core/detector.i"
	@echo "... src/core/detector.s"
	@echo "... src/core/event.o"
	@echo "... src/core/event.i"
	@echo "... src/core/event.s"
	@echo "... src/core/geo_ip.o"
	@echo "... src/core/geo_ip.i"
	@echo "... src/core/geo_ip.s"
	@echo "... src/core/honeypot.o"
	@echo "... src/core/honeypot.i"
	@echo "... src/core/honeypot.s"
	@echo "... src/core/ipaddr.o"
	@echo "... src/core/ipaddr.i"
	@echo "... src/core/ipaddr.s"
	@echo "... src/core/log_watcher.o"
	@echo "... src/core/log_watcher.i"
	@echo "... src/core/log_watcher.s"
	@echo "... src/core/net_util.o"
	@echo "... src/core/net_util.i"
	@echo "... src/core/net_util.s"
	@echo "... src/core/rule_loader.o"
	@echo "... src/core/rule_loader.i"
	@echo "... src/core/rule_loader.s"
	@echo "... src/core/tor_checker.o"
	@echo "... src/core/tor_checker.i"
	@echo "... src/core/tor_checker.s"
	@echo "... src/core/webshell_scanner.o"
	@echo "... src/core/webshell_scanner.i"
	@echo "... src/core/webshell_scanner.s"
	@echo "... src/service/database_helper.o"
	@echo "... src/service/database_helper.i"
	@echo "... src/service/database_helper.s"
	@echo "... src/utilities/logger.o"
	@echo "... src/utilities/logger.i"
	@echo "... src/utilities/logger.s"
	@echo "... src/views/detail_panel.o"
	@echo "... src/views/detail_panel.i"
	@echo "... src/views/detail_panel.s"
	@echo "... src/views/gui_sink.o"
	@echo "... src/views/gui_sink.i"
	@echo "... src/views/gui_sink.s"
	@echo "... src/views/log_model.o"
	@echo "... src/views/log_model.i"
	@echo "... src/views/log_model.s"
	@echo "... test_arena.o"
	@echo "... test_arena.i"
	@echo "... test_arena.s"
	@echo "... test_ipaddr.o"
	@echo "... test_ipaddr.i"
	@echo "... test_ipaddr.s"
	@echo "... test_log_model.o"
	@echo "... test_log_model.i"
	@echo "... test_log_model.s"
	@echo "... test_main.o"
	@echo "... test_main.i"
	@echo "... test_main.s"
	@echo "... test_rule_loader.o"
	@echo "... test_rule_loader.i"
	@echo "... test_rule_loader.s"
	@echo "... test_theme.o"
	@echo "... test_theme.i"
	@echo "... test_theme.s"
	@echo "... test_types.o"
	@echo "... test_types.i"
	@echo "... test_types.s"
	@echo "... test_webshell_scanner.o"
	@echo "... test_webshell_scanner.i"
	@echo "... test_webshell_scanner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

