apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nezhaguard

resources:
  - namespace.yaml
  - configmap.yaml
  - rbac.yaml
  - daemonset.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/part-of: nezhaguard-siem

images:
  - name: nezhaguard
    newTag: latest
